"""
Django settings for slide_management project.

Generated by 'django-admin startproject' using Django 3.0.8.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
import sys

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
print("Base Directory Path: ", BASE_DIR)
print("Version Infosss:", sys.version)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '%&mrvyoxekxi%gj+_lrt6oijom-n$grciss=pf$m38w8zc#3$d'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*', 'slide-management.uralensis.com', 'www.slide-management.uralensis.com', '127.0.0.1',
                 'demo.slide-management.uralensis.com', 'uralensis.com']
# ALLOWED_HOSTS = ['slide-management.uralensis.com', 'www.slide-management.uralensis.com','127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'api',
    'authentication',
    'dashboard'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'slide_management.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'slide_management.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'wpuralen_slides_management',
        'USER': 'root',
        'PASSWORD': 'password123#',
        'HOST': 'localhost',  # Or an IP Address that your DB is hosted on
        'PORT': '3306',
        'OPTIONS': {
            'init_command': 'SET innodb_strict_mode=1',
        }
    }
}

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR + 'db.sqlite3',
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# or, depending on your configuration:
DEFAULT_DOMAIN = '//{}'.format(ALLOWED_HOSTS[0])

LOGIN_URL = '/auth/login'

# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
# STATIC_ROOT = os.path.join(BASE_DIR, 'static/')

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static/'),
)

MEDIA_DIR = "D:\slider-view"

MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

SLIDES_DIR = os.path.join(MEDIA_DIR, 'slides')

LABELS_DIR = os.path.join(BASE_DIR, STATICFILES_DIRS[0], 'images', 'labels')

STATIC_DIR = os.path.join(BASE_DIR, STATICFILES_DIRS[0])

SLIDEFILE_EXTENSIONS = ('.jpg', '.jpeg', '.mrxs', '.tif', '.tiff', '.svs')
DEEPZOOM_FORMAT = "jpeg"
DEEPZOOM_OVERLAP = 1
DEEPZOOM_TILE_SIZE = 256
HISTOSLIDE_SLIDEROOT = BASE_DIR

VALID_SLIDE_EXT = [
    'svs', 'tif',
    'vms', 'vmu', 'ndpi',
    'scn', 'mrxs', 'tiff',
    'svslide',
    'bif',
    'dicom', 'dcm'
]

VALID_SLIDE_TYPE = [('1', 'DICOM'), ('2', 'OpenSlide')]

PATHHUB_REST_USER = 'admin'
PATHHUB_REST_PASSWORD = 'HwuKUP2LrZH5XgQk'
PATHHUB_REST_URL = 'https://demo.uralensiswebapp.co.uk/api/'

X_FRAME_OPTIONS = 'ALLOW-FROM virtualacp.com, ftmsk.uralensiswebapp.co.uk mskcc.uralensisdigital.co.uk mskcc.uralensiswebapp.co.uk demo.uralensiswebapp.co.uk'
CSRF_TRUSTED_ORIGINS = ['virtualacp.com', 'ftmsk.uralensiswebapp.co.uk', 'mskcc.uralesnsisdigital.co.uk',
                        'mskcc.uralensisdigital.co.uk/development', 'mskcc.uralensiswebapp.co.uk',
                        'demo.uralensiswebapp.co.uk']
CSRF_COOKIE_SAMESITE = None

STATIC_ROOT = "statics"

import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration

sentry_sdk.init(
    dsn="https://d14cdcc39fdb4883b8cdf4d5f2d9055b@o1146271.ingest.sentry.io/6214798",
    integrations=[DjangoIntegration()],

    # Set traces_sample_rate to 1.0 to capture 100%
    # of transactions for performance monitoring.
    # We recommend adjusting this value in production.
    traces_sample_rate=1.0,

    # If you wish to associate users to errors (assuming you are using
    # django.contrib.auth) you may enable sending PII data.
    send_default_pii=True
)
