# Generated by Django 2.2.26 on 2022-10-12 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=100, null=True)),
                ('Name', models.CharField(max_length=100)),
                ('Created', models.DateField(auto_now_add=True)),
                ('Modified', models.DateField(auto_now=True)),
                ('Parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent', to='dashboard.Folder')),
            ],
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=100, null=True)),
                ('Name', models.CharField(max_length=50)),
                ('ScannedBy', models.CharField(blank=True, max_length=50)),
                ('ScannedDate', models.DateField(blank=True)),
                ('InsertedBy', models.CharField(blank=True, max_length=50)),
                ('InsertedDate', models.DateField(blank=True)),
                ('SlideType', models.IntegerField(choices=[(1, 'DICOM'), (2, 'openslide')])),
                ('UrlPath', models.CharField(max_length=500)),
                ('LabelUrlPath', models.CharField(max_length=500)),
                ('Group', models.IntegerField(default=0)),
                ('GroupName', models.CharField(default='Default Group', max_length=100)),
                ('Annotations', models.BooleanField(default=False)),
                ('Filesize', models.FloatField(default=0)),
                ('Tag', models.CharField(blank=True, max_length=50)),
                ('CaseNo', models.CharField(blank=True, max_length=50)),
                ('CopyOf', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copy', to='dashboard.Slide')),
                ('Folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Folder')),
            ],
            options={
                'ordering': ['UrlPath'],
            },
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Json', models.TextField()),
                ('AnnotationText', models.TextField()),
                ('Type', models.CharField(max_length=10)),
                ('Slide_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Slide')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Saved', models.BooleanField(default=False)),
                ('LastAccessed', models.DateTimeField()),
                ('Slide_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Slide')),
            ],
        ),
    ]
