# Generated by Django 3.1.6 on 2021-02-26 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_folder_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='Path',
        ),
    ]
