# Generated by Django 3.1.6 on 2021-02-27 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20210227_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='UrlPath',
            field=models.CharField(max_length=500),
        ),
    ]
