# Generated by Django 3.1.6 on 2021-03-01 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20210227_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='LabelUrlPath',
            field=models.CharField(max_length=500),
        ),
    ]
