# Generated by Django 3.1.6 on 2021-03-01 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20210301_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='Tag',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
