# Generated by Django 2.2.26 on 2022-03-11 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_folder_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='organization',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
